# Generated by Django 3.2.23 on 2023-12-01 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('start_odo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_odo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('daily_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_status', models.CharField(choices=[('P', 'PENDING'), ('O', 'ONGOING'), ('A', 'ABORTED'), ('C', 'COMPLETE')], max_length=1)),
                ('next_available_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address_street', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(choices=[('Alabama', 'AL'), ('Alaska', 'AK'), ('Arizona', 'AZ'), ('Arkansas', 'AR'), ('California', 'CA'), ('Colorado', 'CO'), ('Connecticut', 'CT'), ('Delaware', 'DE'), ('Florida', 'FL'), ('Georgia', 'GA'), ('Hawaii', 'HI'), ('Idaho', 'ID'), ('Illinois', 'IL'), ('Indiana', 'IN'), ('Iowa', 'IA'), ('Kansas', 'KS'), ('Kentucky', 'KY'), ('Louisiana', 'LA'), ('Maine', 'ME'), ('Maryland', 'MD'), ('Massachusetts', 'MA'), ('Michigan', 'MI'), ('Minnesota', 'MN'), ('Mississippi', 'MS'), ('Missouri', 'MO'), ('Montana', 'MT'), ('Nebraska', 'NE'), ('Nevada', 'NV'), ('New Hampshire', 'NH'), ('New Jersey', 'NJ'), ('New Mexico', 'NM'), ('New York', 'NY'), ('North Carolina', 'NC'), ('North Dakota', 'ND'), ('Ohio', 'OH'), ('Oklahoma', 'OK'), ('Oregon', 'OR'), ('Pennsylvania', 'PA'), ('Rhode Island', 'RI'), ('South Carolina', 'SC'), ('South Dakota', 'SD'), ('Tennessee', 'TN'), ('Texas', 'TX'), ('Utah', 'UT'), ('Vermont', 'VT'), ('Virginia', 'VA'), ('Washington', 'WA'), ('West Virginia', 'WV'), ('Wisconsin', 'WI'), ('Wyoming', 'WY')], max_length=100)),
                ('address_zipcode', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_class', models.CharField(max_length=100)),
                ('rent_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_charge', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vin_number', models.CharField(max_length=100)),
                ('license_plate_number', models.CharField(max_length=100)),
                ('make_year', models.DateField()),
                ('odo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicleclass')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.officelocation')),
            ],
        ),
        migrations.AddIndex(
            model_name='officelocation',
            index=models.Index(fields=['address_city'], name='vehicle_off_address_f10625_idx'),
        ),
        migrations.AddIndex(
            model_name='officelocation',
            index=models.Index(fields=['address_street'], name='vehicle_off_address_0e768a_idx'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_bookings', to='vehicle.officelocation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_bookings', to='vehicle.officelocation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_bookings', to='vehicle.vehicle'),
        ),
    ]
