# Generated by Django 3.2.23 on 2023-12-09 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swimlane', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('start_odo', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('end_odo', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('daily_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_status', models.CharField(choices=[('P', 'PENDING'), ('O', 'ONGOING'), ('A', 'ABORTED'), ('C', 'COMPLETE')], max_length=1)),
                ('next_available_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('P', 'PENDING'), ('C', 'COMPLETE')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address_street', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=100)),
                ('address_zipcode', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_class', models.CharField(max_length=100)),
                ('rent_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_charge', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vin_number', models.CharField(max_length=100)),
                ('license_plate_number', models.CharField(max_length=100)),
                ('make_year', models.DateField()),
                ('odo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicleclass')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.officelocation')),
            ],
        ),
        migrations.AddIndex(
            model_name='officelocation',
            index=models.Index(fields=['address_city'], name='vehicle_off_address_f10625_idx'),
        ),
        migrations.AddIndex(
            model_name='officelocation',
            index=models.Index(fields=['address_street'], name='vehicle_off_address_0e768a_idx'),
        ),
        migrations.AddField(
            model_name='booking',
            name='coupon_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_coupons', to='swimlane.coupon'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_bookings', to='vehicle.officelocation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ManyToManyField(related_name='paid_bookings', to='swimlane.Payment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_bookings', to='vehicle.officelocation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_bookings', to='vehicle.vehicle'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vehicle_id', 'pickup_date'], name='vehicle_boo_vehicle_be74b4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vehicle_id', 'dropoff_date'], name='vehicle_boo_vehicle_404ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vehicle_id', 'next_available_date'], name='vehicle_boo_vehicle_3b75a3_idx'),
        ),
    ]
