# Generated by Django 3.2.23 on 2023-12-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.CharField(default='Experience elegance and comfort on the rode with us.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rating',
            field=models.IntegerField(default=4),
        ),
    ]
