# Generated by Django 3.2.23 on 2023-12-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vehicle_id', 'pickup_date'], name='vehicle_boo_vehicle_be74b4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vehicle_id', 'dropoff_date'], name='vehicle_boo_vehicle_404ad7_idx'),
        ),
    ]
