# Generated by Django 3.2.23 on 2023-12-08 21:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20231205_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 8, 21, 1, 49, 911099)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('P', 'PENDING'), ('C', 'COMPLETE')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_odo',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_odo',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
