# Generated by Django 3.2.23 on 2023-12-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20231208_2102'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vehicle_id', 'next_available_date'], name='vehicle_boo_vehicle_3b75a3_idx'),
        ),
    ]
