# Generated by Django 3.2.23 on 2023-12-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimlane', '0002_initial'),
        ('vehicle', '0004_booking_vehicle_boo_vehicle_3b75a3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ManyToManyField(null=True, related_name='paid_bookings', to='swimlane.Payment'),
        ),
    ]
