# Generated by Django 3.2.23 on 2023-12-04 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimlane', '0002_initial'),
        ('vehicle', '0004_auto_20231204_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='coupon_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_coupons', to='swimlane.coupon'),
        ),
    ]
