# Generated by Django 3.2.23 on 2023-12-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_invoice_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='taxes',
            field=models.FloatField(default=18),
            preserve_default=False,
        ),
    ]
