# Generated by Django 3.2.23 on 2023-12-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimlane', '0002_initial'),
        ('vehicle', '0005_booking_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.ManyToManyField(related_name='paid_bookings', to='swimlane.Payment'),
        ),
    ]
