# Generated by Django 3.2.23 on 2023-12-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_auto_20231210_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='goods_and_services_tax',
        ),
    ]
