# Generated by Django 3.2.23 on 2023-12-12 05:16

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_remove_invoice_goods_and_services_tax'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('end_odo__gt', django.db.models.expressions.F('start_odo'))), name='dsr_booking_chk_odo'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('dropoff_date__gt', django.db.models.expressions.F('pickup_date'))), name='dsr_booking_chk_service_date'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('trip_status__in', ['P', 'O', 'A', 'C'])), name='dsr_booking_chk_service_status'),
        ),
    ]
