# Generated by Django 3.2.23 on 2023-12-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20231212_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='url',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
