# Generated by Django 3.2.23 on 2023-12-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('user_type__in', ['I', 'C'])), name='ch_inh_dsr_customer'),
        ),
    ]
