# Generated by Django 3.2.23 on 2023-11-23 04:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('corp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100, validators=[django.core.validators.URLValidator])),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coupon_type', models.CharField(choices=[('I', 'INDIVIDUAL'), ('C', 'CORPORATE')], max_length=1)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_number', models.CharField(max_length=100)),
                ('insurance_company', models.CharField(max_length=100)),
                ('insurance_policy_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('C', 'CREDIT'), ('D', 'DEBIT'), ('G', 'GIFT')], max_length=1)),
                ('card_number', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponCorporate',
            fields=[
                ('coupon_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='swimlane.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='CouponIndividual',
            fields=[
                ('coupon_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='swimlane.coupon')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
            ],
        ),
    ]
