# Generated by Django 3.2.23 on 2023-12-09 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swimlane', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerindividual',
            name='customer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='corp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimlane.corporation'),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='customer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['coupon_code'], name='swimlane_co_coupon__b6bd8d_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['coupon_id', 'coupon_code'], name='swimlane_co_coupon__82dbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='corporation',
            index=models.Index(fields=['domain'], name='swimlane_co_domain_549738_idx'),
        ),
        migrations.AddField(
            model_name='couponcorporate',
            name='corp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimlane.corporation'),
        ),
    ]
