# Generated by Django 3.2.23 on 2023-12-01 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swimlane', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerindividual',
            name='customer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='corp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimlane.corporation'),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='customer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='corporation',
            index=models.Index(fields=['domain'], name='swimlane_co_domain_549738_idx'),
        ),
        migrations.AddField(
            model_name='couponcorporate',
            name='corp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimlane.corporation'),
        ),
    ]
