# Generated by Django 3.2.23 on 2023-12-12 05:13

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('swimlane', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('coupon_type__in', ['I', 'C'])), name='ch_inh_dsr_coupon'),
        ),
        migrations.AddConstraint(
            model_name='couponindividual',
            constraint=models.CheckConstraint(check=models.Q(('valid_to__gte', django.db.models.expressions.F('valid_from'))), name='dsr_coupon_indiv_chk_date'),
        ),
    ]
