# Generated by Django 3.2.23 on 2023-12-04 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swimlane', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercorporate',
            name='customer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerindividual',
            name='customer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
