# Generated by Django 3.2.23 on 2023-12-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimlane', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='a', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
