# Generated by Django 3.2.23 on 2023-12-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimlane', '0003_coupon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='code',
            new_name='coupon_code',
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['coupon_code'], name='swimlane_co_coupon__b6bd8d_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['coupon_id', 'coupon_code'], name='swimlane_co_coupon__82dbcc_idx'),
        ),
    ]
