# Generated by Django 3.2.23 on 2023-12-04 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimlane', '0003_auto_20231204_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='exp_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='rohit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='zipcode',
            field=models.CharField(default='11209', max_length=5),
            preserve_default=False,
        ),
    ]
