# Generated by Django 3.2.23 on 2023-12-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimlane', '0004_auto_20231204_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='exp_date',
            new_name='card_exp_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='name',
            new_name='card_name',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='zipcode',
            new_name='card_zipcode',
        ),
    ]
